### ISSUE TITLE
Node 10 fails tests on Travis

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal-core#54] opened 2019-08-18 17:56 UTC
https://travis-ci.org/cabal-club/cabal-core/builds/573479099

**Comment by vweevers** [comment] 2019-08-18 19:06
It looks like a level issue so I got interested. I'm able to replicate locally on node 6, 8, 10, 12. Diving in.

**Comment by vweevers** [comment] 2019-08-18 19:18
@noffle The problem is the use of `memdb`, which is 3/4 years old and depends on `memdown@1`, and `subleveldown` (when it attempts to "unwrap" the db to find the innermost db) doesn't recognize that version of `memdown` as an `abstract-leveldown` implementation.

I'll see if we can relax that mechanism a bit.

I also recommend replacing `memdb`  with `level-mem`.

**Comment by vweevers** [comment] 2019-08-18 19:58
Fixed in `subleveldown@4.1.1`. Should float in automatically here.

> I also recommend replacing memdb with level-mem.

On second thought, wait a bit. In a few days I'll release a new major of `level-mem` which brings its behavior closer to `leveldown` (long story), which y'all will benefit from.

**Comment by cblgh** [comment] 2019-08-18 20:12
wow @vweevers yr the mvp, thanks so much for taking this on 🖤

**Comment by noffle** [comment] 2019-08-19 05:01
@vweevers :heart:!!!

**Comment by cblgh** [comment] 2020-03-20 14:51
fixed ^

**Closed by cblgh** 2020-03-20 14:51 UTC
Labels: bug, help wanted
